[package]
name = "spinoso-random"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = """
Implementation of Ruby Random Core class.
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["random", "rand", "rng", "mt", "spinoso"]
categories = ["algorithms", "no-std"]

[dependencies]
getrandom = { version = "0.2", default-features = false }
libm = "0.2"
rand_ = { version = "0.7", optional = true, default-features = false, package = "rand" }
rand_core_ = { version = "0.5", optional = true, default-features = false, package = "rand_core" }

[features]
default = ["rand", "std"]
# Enables range sampling methods for the `rand()` function.
rand = ["rand_", "rand_core"]
# Enables implementations of `RngCore` on `Random` and `Mt` types.
rand_core = ["rand_core_"]
std = []
